<a href="https://colab.research.google.com/github/Shanthinimurugan/Exploring-Data-with-NumPy-and-Pandas/blob/main/Exploring_Data_with_NumPy_and_Pandas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Exploring Data with NumPy and Pandas

**🎯 Objective**

The exploration of data analysis using NumPy and Pandas in Python covers NumPy array creation, indexing, slicing, numerical operations, and basic statistical calculations, along with Pandas Series and DataFrame creation, data exploration, filtering, grouping, and manipulation.

The assignment uses temperature and transaction datasets to practice fundamental data handling and analysis techniques in Python.

**📌 Problem Statement**

• Analyze weekly temperature data using NumPy by creating 1D and 2D arrays, performing Celsius-to-Fahrenheit conversion, finding maximum, minimum, and mean temperatures, and extracting specific days using indexing and slicing.

• Use Pandas Series to work with student marks by applying custom indexing, loc, iloc, boolean filtering, and Series manipulation such as updating, deleting, and calculating CGPA.

• Create a transactions DataFrame containing transaction ID, product category, region, and amount. Explore the dataset using basic DataFrame information, column selection, filtering, value counts, unique values, and grouping. Then modify the transaction amount, calculate a discount, remove a transaction, and delete the discount column.

**Tasks Performed:**

### Numpy Array Operations:

In [ ]:
!pip install numpy

Requirement already satisfied: numpy in /usr/local/lib/python3.13/dist-packages (2.1.3)

In [ ]:
import numpy as np

In [ ]:
# 1. Create a 1D NumPy Array:

temperatures_w1 = np. array([22.5, 25.3, 20.8, 23.4, 26.1, 24.8, 21.9])
temperatures_w1

array([22.5, 25.3, 20.8, 23.4, 26.1, 24.8, 21.9])

In [ ]:
# 2. Inspection and Properties:
# ● Inspect the shape, data type, and the number of elements in the array

print("Shape: ",temperatures_w1.shape)
print("Object data type: ",type(temperatures_w1))
print("Element data type: ", temperatures_w1.dtype)
print("Dimension: ",temperatures_w1.ndim)
print("Number of Elements: ",temperatures_w1.size)

Shape:  (7,)
Object data type:  <class 'numpy.ndarray'>
Element data type:  float64
Dimension:  1
Number of Elements:  7

In [ ]:
# 3. Array Operations:
#  Convert the temperatures_w1 from Celsius to Fahrenheit
# Fahrenheit = (Celsius * 9/5) + 32

Fahrenheit = (temperatures_w1*9/5)+32
print("Fahrenheit: ",Fahrenheit)

# ● Find the maximum, minimum, and mean temperatures for the week.

print("Mean temperatures: ",round(np.mean(temperatures_w1), 2))
print("Minimum temperature: ",np.min(temperatures_w1))
print("Maximum temperature: ",np.max(temperatures_w1))

Fahrenheit:  [72.5  77.54 69.44 74.12 78.98 76.64 71.42]
Mean temperatures:  23.54
Minimum temperature:  20.8
Maximum temperature:  26.1

In [ ]:
# 4. Array Slicing and Indexing:
# ● Extract the temperatures for the first three days of the week.

print("First three days of teperatures: ",temperatures_w1[0:3].tolist())
# [22.5, 25.3, 20.8, 23.4, 26.1, 24.8, 21.9]

# ● Extract the temperatures for the weekend (last two days).

print("Weekend temperatures: ",temperatures_w1[-2:].tolist())

# ● Extract the temperatures for the middle three days of the week.

print("Middle three days of temperatures: ",temperatures_w1[2:5].tolist())

First three days of teperatures:  [22.5, 25.3, 20.8]
Weekend temperatures:  [24.8, 21.9]
Middle three days of temperatures:  [20.8, 23.4, 26.1]

In [ ]:
# 5. Create a 2D Array:
temperatures = np.array([[22.5, 25.3, 20.8, 23.4, 26.1, 24.8, 21.9],
                        [19.2, 22.5, 21.3, 24.0, 23.5, 22.8, 20.1]])
temperatures

array([[22.5, 25.3, 20.8, 23.4, 26.1, 24.8, 21.9],
       [19.2, 22.5, 21.3, 24. , 23.5, 22.8, 20.1]])

In [ ]:
# 6. Inspect and Slice the 2D Array:
# ● Inspect and print the shape, data type, and total number of elements in the temperatures array.

print("Shape: ",temperatures.shape)
print("Object data type: ",type(temperatures))
print("Element data type: ",temperatures.dtype)
print("Dimension: ",temperatures.ndim)
print("Number of Elements: ",temperatures.size)

Shape:  (2, 7)
Object data type:  <class 'numpy.ndarray'>
Element data type:  float64
Dimension:  2
Number of Elements:  14

In [ ]:
# ● Extract the temperatures for each week and the weekends (last two days) for both weeks
print("Week 1 temperatures: ",temperatures[0].tolist())
print("Week 2 temperatures: ",temperatures[1].tolist())
print("Weekend temperatures: ",temperatures[0:2,-2:].tolist())

Week 1 temperatures:  [22.5, 25.3, 20.8, 23.4, 26.1, 24.8, 21.9]
Week 2 temperatures:  [19.2, 22.5, 21.3, 24.0, 23.5, 22.8, 20.1]
Weekend temperatures:  [[24.8, 21.9], [22.8, 20.1]]

### Pandas Series:

In [ ]:
!pip install pandas

Requirement already satisfied: pandas in /usr/local/lib/python3.13/dist-packages (2.2.3)
Requirement already satisfied: numpy>=1.26.0 in /usr/local/lib/python3.13/dist-packages (from pandas) (2.1.3)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.13/dist-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.13/dist-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.13/dist-packages (from pandas) (2026.3)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.13/dist-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

In [ ]:
import pandas as pd

In [ ]:

# 1. Creating Pandas Series:

marks_ser = pd.Series([95, 92, 89, 85, 80], index=['Rank1', 'Rank2', 'Rank3', 'Rank4', 'Rank5'],name="marks")
marks_ser

Rank1    95
Rank2    92
Rank3    89
Rank4    85
Rank5    80
Name: marks, dtype: int64

In [ ]:
# 2. Indexing and Slicing:

# ● Use the integer index position to access the mark of the 1st rank student.

print("Mark of the 1st rank student: ",marks_ser.iloc[0],"\n")

# ● Use the loc accessor to retrieve the marks of the top 3 ranks by specifying their index labels.

print("Marks of the top 3 ranks:")
print(marks_ser.loc["Rank1":"Rank3"],"\n")

# ● Use the iloc accessor to retrieve the mark of the 3rd-ranked student.

print("Mark of the 3rd-ranked student: ",marks_ser.iloc[2],"\n")

# ● Apply a boolean mask to filter the Series and retrieve the ranks where the marks are greater than 90.
print("Marks greater than 90:")
print(marks_ser.loc[marks_ser>90])

Mark of the 1st rank student:  95

Marks of the top 3 ranks:
Rank1    95
Rank2    92
Rank3    89
Name: marks, dtype: int64

Mark of the 3rd-ranked student:  89

Marks greater than 90:
Rank1    95
Rank2    92
Name: marks, dtype: int64

In [ ]:
# 3. Manipulating Series:
# ● Modify the mark of the student with the 1st rank to 100.

marks_ser.loc["Rank1"]=100
marks_ser

Rank1    100
Rank2     92
Rank3     89
Rank4     85
Rank5     80
Name: marks, dtype: int64

In [ ]:
# ● Remove the entry corresponding to the last rank from the Series.
marks_ser.drop('Rank5',inplace=True)
marks_ser

Rank1    95
Rank2    92
Rank3    89
Rank4    85
Name: marks, dtype: int64

In [ ]:
# ● Compute the CGPA by dividing each mark in the Series by 10.

CGPA = marks_ser/10
CGPA

Rank1    9.5
Rank2    9.2
Rank3    8.9
Rank4    8.5
Name: marks, dtype: float64

### Pandas DataFrame:

In [ ]:
# 1. Creating Pandas DataFrame:

transactions = pd.DataFrame({
    "TransactionID": [101, 102, 103, 104, 105, 106, 107, 108, 109, 110],
    "ProductCategory": ['Electronics', 'Clothing', 'Electronics', 'Furniture', 'Clothing',
'Electronics', 'Furniture', 'Clothing', 'Furniture', 'Electronics'],
    "Region": ['North', 'South', 'North', 'East', 'West', 'North', 'East', 'West', 'South',
'North'],
    "Amount": [200, 150, 300, 450, 200, 250, 300, 180, 350, 400]
})
transactions

   TransactionID ProductCategory Region  Amount
0            101     Electronics  North     200
1            102        Clothing  South     150
2            103     Electronics  North     300
3            104       Furniture   East     450
4            105        Clothing   West     200
5            106     Electronics  North     250
6            107       Furniture   East     300
7            108        Clothing   West     180
8            109       Furniture  South     350
9            110     Electronics  North     400

In [ ]:
# 2. Data Exploration:
# ● Display the transactions DataFrame and its basic information, including head, tail,
# shape, column names, and data types.

transactions.head()

   TransactionID ProductCategory Region  Amount
0            101     Electronics  North     200
1            102        Clothing  South     150
2            103     Electronics  North     300
3            104       Furniture   East     450
4            105        Clothing   West     200

In [ ]:
transactions.tail()

   TransactionID ProductCategory Region  Amount
5            106     Electronics  North     250
6            107       Furniture   East     300
7            108        Clothing   West     180
8            109       Furniture  South     350
9            110     Electronics  North     400

In [ ]:
transactions.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 4 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   TransactionID    10 non-null     int64
 1   ProductCategory  10 non-null     object
 2   Region           10 non-null     object
 3   Amount           10 non-null     int64
dtypes: int64(2), object(2)
memory usage: 452.0+ bytes

In [ ]:
transactions.describe()

       TransactionID      Amount
count       10.00000   10.000000
mean       105.50000  278.000000
std          3.02765   99.755256
min        101.00000  150.000000
25%        103.25000  200.000000
50%        105.50000  275.000000
75%        107.75000  337.500000
max        110.00000  450.000000

In [ ]:
print("Shape: ",transactions.shape)
print("Column Names: ",transactions.columns,"\n")
print(transactions.dtypes)

Shape:  (10, 4)
Column Names:  Index(['TransactionID', 'ProductCategory', 'Region', 'Amount'], dtype='object')

TransactionID       int64
ProductCategory    object
Region             object
Amount              int64
dtype: object

In [ ]:
# ● Display only the 'ProductCategory' and 'Amount' columns.

transactions[['ProductCategory', 'Amount']]

  ProductCategory  Amount
0     Electronics     200
1        Clothing     150
2     Electronics     300
3       Furniture     450
4        Clothing     200
5     Electronics     250
6       Furniture     300
7        Clothing     180
8       Furniture     350
9     Electronics     400

In [ ]:
# ● Retrieve the last 3 columns of the DataFrame using iloc or loc.

transactions.iloc[:,-3:]
# or
transactions.loc[:,"ProductCategory":"Amount"]

  ProductCategory Region  Amount
0     Electronics  North     200
1        Clothing  South     150
2     Electronics  North     300
3       Furniture   East     450
4        Clothing   West     200
5     Electronics  North     250
6       Furniture   East     300
7        Clothing   West     180
8       Furniture  South     350
9     Electronics  North     400

In [ ]:
# ● Filter rows where the 'Region' is 'North' and 'Amount' is greater than 200.

transactions[(transactions['Region']=="North") & (transactions['Amount'] > 200)]

   TransactionID ProductCategory Region  Amount
2            103     Electronics  North     300
5            106     Electronics  North     250
9            110     Electronics  North     400

In [ ]:
# ● Find the value counts for the 'ProductCategory' column.

transactions["ProductCategory"].value_counts()

ProductCategory
Electronics    4
Clothing       3
Furniture      3
Name: count, dtype: int64

In [ ]:

# ● Find the unique values in the 'Region' column.

transactions["Region"].unique()

array(['North', 'South', 'East', 'West'], dtype=object)

In [ ]:
# ● Group by 'Region' and find the mean amount for each region.

transactions.groupby("Region")["Amount"].mean()

Region
East     375.0
North    287.5
South    250.0
West     190.0
Name: Amount, dtype: float64

In [ ]:
# 3. Manipulating the DataFrame:
# ● Modify the 'Amount' for the transaction with TransactionID 102 to 165.

transactions.loc[1,"Amount"]=165

# or
transactions.loc[transactions["TransactionID"] == 102, "Amount"] = 165
transactions

   TransactionID ProductCategory Region  Amount
0            101     Electronics  North     200
1            102        Clothing  South     165
2            103     Electronics  North     300
3            104       Furniture   East     450
4            105        Clothing   West     200
5            106     Electronics  North     250
6            107       Furniture   East     300
7            108        Clothing   West     180
8            109       Furniture  South     350
9            110     Electronics  North     400

In [ ]:
# ● Add a new column 'Discount' by calculating 10% of the 'Amount'.

transactions["Discount"]=(transactions["Amount"]*10)/100
transactions

   TransactionID ProductCategory Region  Amount  Discount
0            101     Electronics  North     200      20.0
1            102        Clothing  South     165      16.5
2            103     Electronics  North     300      30.0
3            104       Furniture   East     450      45.0
4            105        Clothing   West     200      20.0
5            106     Electronics  North     250      25.0
6            107       Furniture   East     300      30.0
7            108        Clothing   West     180      18.0
8            109       Furniture  South     350      35.0
9            110     Electronics  North     400      40.0

In [ ]:
# ● Remove the row with TransactionID 109.

transactions.drop(transactions[transactions["TransactionID"] == 109].index, inplace= True)
transactions

   TransactionID ProductCategory Region  Amount  Discount
0            101     Electronics  North     200      20.0
1            102        Clothing  South     165      16.5
2            103     Electronics  North     300      30.0
3            104       Furniture   East     450      45.0
4            105        Clothing   West     200      20.0
5            106     Electronics  North     250      25.0
6            107       Furniture   East     300      30.0
7            108        Clothing   West     180      18.0
9            110     Electronics  North     400      40.0

In [ ]:
# ● Delete the 'Discount' column from the DataFrame.

transactions.drop("Discount",axis=1,inplace=True)
transactions

   TransactionID ProductCategory Region  Amount
0            101     Electronics  North     200
1            102        Clothing  South     165
2            103     Electronics  North     300
3            104       Furniture   East     450
4            105        Clothing   West     200
5            106     Electronics  North     250
6            107       Furniture   East     300
7            108        Clothing   West     180
9            110     Electronics  North     400

**✅ Conclusion**

This assignment provided practical experience in using NumPy and Pandas for data analysis. It helped develop skills in working with arrays, Series, and DataFrames, along with indexing, filtering, slicing, aggregation, and data manipulation techniques using real-world temperature and transaction datasets.